import "./globals.scss";
import "swiper/css";
import "swiper/css/navigation";
import "../../public/css/bootstrap.min.css";
import "../../public/css/style.css";
import Layout from "./components/layout/Layout";
import "../../public/css/responsive.css";
import { Inter } from "next/font/google";
import { createSharedPathnamesNavigation } from "next-intl/navigation";

import {
  NextIntlClientProvider,
  useMessages,
} from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FIRE! FIRE!",
  description: "Generated by create next app",
};
const locales = ["az", "en", "ru"];

export default function LocaleLayout({ children, params: { locale } }) {
  if (!locales.includes(locale)) notFound();
  const messages = useMessages();
  const { Link, redirect, usePathname, useRouter } =
    createSharedPathnamesNavigation({ locales });


  return (
    <html lang={locale}>

      <NextIntlClientProvider locale={locale} messages={messages}>
        <body className={inter.className}>

          <Layout HeaderStyle="three">
            {children}
          </Layout>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
